modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="sky_isles"
version="1.20.1-1.0.0"
displayName="Sky Isles"
displayURL="https://discordapp.com/users/555629040455909406"
authors="mattwhyy"
description="Skyblock island generation mod"

[[dependencies.sky_isles]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

